# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oclaw < Formula
  desc "Terminal UI for OpenClaw agent chat"
  homepage "https://github.com/quantum-bytes/oclaw"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quantum-bytes/oclaw/releases/download/v0.1.0/oclaw_0.1.0_darwin_amd64.tar.gz"
      sha256 "00df94f6f5c40c5433f361e172613f1fcd309cd0d0be1bf99cab514437dc084d"

      define_method(:install) do
        bin.install "oclaw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quantum-bytes/oclaw/releases/download/v0.1.0/oclaw_0.1.0_darwin_arm64.tar.gz"
      sha256 "8b8109f892debeaea3070e672306384ac5c59c5d322f50c1f357974ef3752712"

      define_method(:install) do
        bin.install "oclaw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantum-bytes/oclaw/releases/download/v0.1.0/oclaw_0.1.0_linux_amd64.tar.gz"
      sha256 "b3d2f585acace5b844af835f481512bd709c3925052090636e64b2a354eb84d7"
      define_method(:install) do
        bin.install "oclaw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantum-bytes/oclaw/releases/download/v0.1.0/oclaw_0.1.0_linux_arm64.tar.gz"
      sha256 "be84376f1bf17b946b4a556ddf723608db81733e668e6c8148bd60cee0753724"
      define_method(:install) do
        bin.install "oclaw"
      end
    end
  end
end
