# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oclaw < Formula
  desc "Terminal UI for OpenClaw agent chat"
  homepage "https://github.com/quantum-bytes/oclaw"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/quantum-bytes/oclaw/releases/download/v0.1.0/oclaw_0.1.0_darwin_amd64.tar.gz"
      sha256 "b4ff29a6131fc22edd686eb354b3b4d73172c179d180b15e2f48f38e3c3bfa7d"

      define_method(:install) do
        bin.install "oclaw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/quantum-bytes/oclaw/releases/download/v0.1.0/oclaw_0.1.0_darwin_arm64.tar.gz"
      sha256 "741ccedec66ddb785c29dfca891b78003a34d50095d29387b8710b077e3ff9ad"

      define_method(:install) do
        bin.install "oclaw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantum-bytes/oclaw/releases/download/v0.1.0/oclaw_0.1.0_linux_amd64.tar.gz"
      sha256 "e67da9d1101499e8c8776f96a832c7b5dd38b24390fd44e17bf18bae801fe1b7"
      define_method(:install) do
        bin.install "oclaw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quantum-bytes/oclaw/releases/download/v0.1.0/oclaw_0.1.0_linux_arm64.tar.gz"
      sha256 "bd7d4162e9e4ec2cef9d87041f2e0a61c473f32198015efd1770b55fdae7daca"
      define_method(:install) do
        bin.install "oclaw"
      end
    end
  end
end
